version: "3"
services:
  backend:
    image: "jasujm/bridgeapp-backend"
    build: "backend/"
    ports:
    - "8000:8000"
    environment:
    - "bridgeapp_backend_endpoint=tcp://bridge:5555"
    command: >-
      gunicorn -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker bridgeapp:app
    env_file:
    - "./.env.backend"
  bridge:
    image: "jasujm/bridge"
    entrypoint: >-
      bridge --config /etc/bridge/config.lua
    volumes:
    - "./config/bridge:/etc/bridge:ro"
    env_file:
    - "./.env.bridge"
