version: "3"
services:
  frontend:
    image: "jasujm/bridgeapp-frontend"
    build: "frontend/"
    entrypoint: >-
      /bin/bash -c 'cp -rf dist/* /var/www/frontend'
    volumes:
    - "frontendwww:/var/www/frontend"
  backend:
    image: "jasujm/bridgeapp-backend"
    build: "backend/"
    environment:
    - "bridgeapp_backend_endpoint=tcp://bridge:5555"
    - "bridgeapp_backend_event_endpoint=tcp://bridge:5556"
    command: >-
      gunicorn -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker bridgeapp
    env_file:
    - "./.env.backend"
  bridge:
    image: "jasujm/bridge"
    entrypoint: >-
      bridge --config /etc/bridge/config.lua
    volumes:
    - "./config/bridge:/etc/bridge:ro"
    env_file:
    - "./.env.bridge"
  nginx:
    image: "nginx"
    ports:
    - "80:80"
    - "443:443"
    entrypoint: >-
      /bin/bash -c "trap 'kill $$(jobs -p)' EXIT;

      function process_config {
        envsubst '$$server_name' < /etc/nginx/conf.d/$${1}.conf.in \
          > /etc/nginx/conf.d/$${1}.conf
      };

      while :; do
        sleep 1d;
        nginx -s reload;
      done &
      process_config default;
      if [ -d /etc/letsencrypt/live/$${server_name} ]; then
        process_config bridgeapp;
      fi;
      nginx -g 'daemon off;'"
    env_file:
    - "./.env.nginx"
    volumes:
    - "frontendwww:/var/www/frontend:ro"
    - "certbotetc:/etc/letsencrypt:ro"
    - "certbotwww:/var/www/certbot:ro"
    - "./config/nginx:/etc/nginx/conf.d"
  certbot:
    image: "certbot/certbot"
    entrypoint: >-
      /bin/sh -c "trap exit TERM;
      while :;
        do certbot renew;
        sleep 1d;
      done;"
    volumes:
    - "certbotetc:/etc/letsencrypt"
    - "certbotwww:/var/www/certbot"
    depends_on:
    - "nginx"
volumes:
  frontendwww:
  certbotetc:
  certbotwww:
