version: "3"
services:
  frontend:
    image: "jasujm/bridgeapp-frontend"
    build: "frontend/"
    entrypoint: >-
      /bin/bash -c 'cp -rf dist/* /var/www/frontend'
    volumes:
    - "frontendwww:/var/www/frontend"
    restart: always
  backend:
    image: "jasujm/bridgeapp-backend"
    build: "backend/"
    environment:
    - "bridgeapp_backend_endpoint=tcp://bridge:5555"
    - "bridgeapp_backend_event_endpoint=tcp://bridge:5556"
    - "bridgeapp_elasticsearch_host=elasticsearch:9200"
    env_file:
    - "./.env.backend"
    restart: always
  bridge:
    image: "jasujm/bridge"
    entrypoint: >-
      bridge --config /etc/bridge/config.lua
    volumes:
    - "./config/bridge:/etc/bridge:ro"
    - "bridgedata:/var/lib/bridge:rw"
    environment:
    - "bridge_data_dir=/var/lib/bridge"
    env_file:
    - "./.env.bridge"
    restart: always
  db:
    image: "postgres:13"
    volumes:
    - "dbdata:/var/lib/postgresql/data:rw"
    env_file:
    - "./.env.postgres"
    restart: always
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.16.2"
    environment:
    - "discovery.type=single-node"
    volumes:
    - "elasticsearchdata:/usr/share/elasticsearch/data:rw"
    restart: always
  nginx:
    image: "jasujm/bridgeapp-nginx"
    build: "nginx/"
    ports:
    - "80:80"
    - "443:443"
    env_file:
    - "./.env.nginx"
    volumes:
    - "frontendwww:/var/www/frontend:ro"
    - "certbotetc:/etc/letsencrypt:ro"
    - "certbotwww:/var/www/certbot:ro"
    - "./nginx/conf.d.in:/etc/nginx/conf.d.in:ro"
    - "./nginx/inc.d:/etc/nginx/inc.d:ro"
    restart: always
  certbot:
    image: "certbot/certbot"
    entrypoint: >-
      /bin/sh -c "trap exit TERM;
      while :;
        do certbot renew;
        sleep 1d;
      done;"
    volumes:
    - "certbotetc:/etc/letsencrypt"
    - "certbotwww:/var/www/certbot"
    depends_on:
    - "nginx"
    restart: always
volumes:
  bridgedata:
  frontendwww:
  dbdata:
  elasticsearchdata:
  certbotetc:
  certbotwww:
